language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r tests/requirements.txt --use-mirrors"
  - "nosetests -w tests --with-gae --without-sandbox -v"
# command to run tests
script: tests/runtests.py --with-pep8
